# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Micronaut Joint Validation Build"
on:
  push:
    branches:
      - GROOVY_3_0_X
  pull_request:
    branches:
      - GROOVY_3_0_X
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        java: [11.0.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: env
        run: env

      # Create mavenLocal init script
      - name: Create init script to enable mavenLocal()
        run: cd .. && echo "allprojects { repositories { mavenLocal() } }" > maven-local-init.gradle

      # Clone Micronaut Repos
      - name: Checkout Micronaut Core
        run: cd .. && git clone --depth 1 https://github.com/micronaut-projects/micronaut-core -b 2.3.x

      - name: Checkout Micronaut Groovy
        run: cd .. && git clone --depth 1 https://github.com/micronaut-projects/micronaut-groovy -b master

      - name: Build and install groovy (no docs)
        run: ./gradlew clean install -x groovydoc -x javadoc -x javadocAll -x groovydocAll -x asciidoc -x docGDK --no-build-cache --no-scan --no-daemon
        timeout-minutes: 60

      - name: Set CI_GROOVY_VERSION
        run: echo "CI_GROOVY_VERSION=$(cat gradle.properties | grep groovyVersion | cut -d\= -f2 |  tr -d '[:space:]')" >> $GITHUB_ENV
      - name: echo CI_GROOVY_VERSION
        run: echo $CI_GROOVY_VERSION

      - name: Check Micronaut Core
        run: cd ../micronaut-core && ./gradlew clean check --no-build-cache --no-scan --no-daemon -PgroovyVersion=$CI_GROOVY_VERSION --init-script ../maven-local-init.gradle
        timeout-minutes: 60

      - name: Check Micronaut Groovy
        run: cd ../micronaut-groovy && ./gradlew clean check --no-build-cache --no-scan --no-daemon -PgroovyVersion=$CI_GROOVY_VERSION --init-script ../maven-local-init.gradle
        timeout-minutes: 60
